# Generated by Django 5.1.3 on 2024-11-15 09:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewSchoolMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=45)),
                ('second_name', models.CharField(max_length=45)),
                ('family_name', models.CharField(max_length=45)),
                ('member_title', models.CharField(max_length=75)),
                ('member_industry', models.CharField(blank=True, max_length=75, null=True)),
                ('member_mobile', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('employment_status', models.CharField(blank=True, choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('CT', 'Contractor'), ('IN', 'Intern')], max_length=75, null=True)),
                ('member_country', models.CharField(blank=True, choices=[('KE', 'Kenya'), ('TZ', 'Tanzania'), ('UG', 'Uganda'), ('RW', 'Rwanda'), ('ZW', 'Zimbabwe'), ('SA', 'South Africa'), ('MZ', 'Mozambique'), ('GH', 'Ghana'), ('UAE', 'United Arab Emirates'), ('NO', 'Norway'), ('FR', 'France'), ('IT', 'Italy')], max_length=75, null=True)),
                ('member_email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('guest', 'Guest')], default='member', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('tenant_name', models.CharField(max_length=255)),
                ('tenant_domain', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='http://localhost:5173/images/default.jpg', null=True, upload_to='profile_images/')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('second_name', models.CharField(max_length=45)),
                ('family_name', models.CharField(max_length=45)),
                ('mobile_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('member_title', models.CharField(max_length=75)),
                ('member_email', models.EmailField(default='abc@company.com', max_length=75)),
                ('member_industry', models.CharField(blank=True, max_length=75, null=True)),
                ('employment_industry', models.CharField(max_length=75)),
                ('date_of_application', models.DateField(auto_now_add=True)),
                ('reason_for_joining', models.TextField(blank=True, null=True)),
                ('referred_by_name', models.CharField(blank=True, max_length=75, null=True)),
                ('referred_by_mobile', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('vetted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('member_joining_date', models.DateField(blank=True, null=True)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='newschoolmember',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.tenant'),
        ),
    ]
