# Generated by Django 5.1.1 on 2024-10-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewSchoolMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('second_name', models.CharField(max_length=45)),
                ('family_name', models.CharField(max_length=45)),
                ('member_title', models.CharField(max_length=75)),
                ('member_years_of_experience', models.IntegerField()),
                ('previous_employer', models.CharField(max_length=75)),
                ('previous_employer2', models.CharField(max_length=75)),
                ('previous_jobtitle', models.CharField(max_length=75)),
                ('previous_jobtitle2', models.CharField(max_length=75)),
                ('member_username', models.CharField(max_length=100)),
                ('member_password', models.CharField(max_length=100)),
            ],
        ),
    ]
