# Generated by Django 5.1.1 on 2024-10-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newschoolmember',
            name='previous_employer3',
            field=models.CharField(default='Third Employer', max_length=75),
        ),
        migrations.AddField(
            model_name='newschoolmember',
            name='previous_employer4',
            field=models.CharField(default='Fourth Employer', max_length=75),
        ),
        migrations.AddField(
            model_name='newschoolmember',
            name='previous_employer5',
            field=models.CharField(default='Fifth Employer', max_length=75),
        ),
        migrations.AddField(
            model_name='newschoolmember',
            name='previous_jobtitle3',
            field=models.CharField(default='Prev Job title3', max_length=75),
        ),
        migrations.AddField(
            model_name='newschoolmember',
            name='previous_jobtitle4',
            field=models.CharField(default='Prev job title 4', max_length=75),
        ),
        migrations.AddField(
            model_name='newschoolmember',
            name='previous_jobtitle5',
            field=models.CharField(default='Prev Job title5', max_length=75),
        ),
    ]
