# Generated by Django 5.1.1 on 2024-10-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_newschoolmember_previous_employer3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newschoolmember',
            name='member_email',
            field=models.CharField(default='abc@company.com', max_length=45),
        ),
        migrations.AddField(
            model_name='newschoolmember',
            name='member_mobile',
            field=models.CharField(default='No Mobile', max_length=45),
        ),
    ]
