# Generated by Django 5.1.1 on 2024-11-13 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_tenant_tenant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenthistory',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.tenant'),
        ),
    ]
