# Generated by Django 5.1.1 on 2024-11-14 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_employmenthistory_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newschoolmember',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolio.tenant'),
            preserve_default=False,
        ),
    ]
