# Generated by Django 5.1.1 on 2024-10-04 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_newschoolmember_member_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newschoolmember',
            name='previous_employer',
        ),
        migrations.RemoveField(
            model_name='newschoolmember',
            name='previous_jobtitle',
        ),
        migrations.AddField(
            model_name='newschoolmember',
            name='previous_employer1',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='newschoolmember',
            name='previous_jobtitle1',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='newschoolmember',
            name='member_email',
            field=models.EmailField(default='abc@company.com', max_length=75),
        ),
        migrations.AlterField(
            model_name='newschoolmember',
            name='member_mobile',
            field=models.CharField(default='No Mobile', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='newschoolmember',
            name='previous_employer2',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='newschoolmember',
            name='previous_employer3',
            field=models.CharField(blank=True, default='Third Employer', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='newschoolmember',
            name='previous_employer4',
            field=models.CharField(blank=True, default='Fourth Employer', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='newschoolmember',
            name='previous_employer5',
            field=models.CharField(blank=True, default='Fifth Employer', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='newschoolmember',
            name='previous_jobtitle2',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='newschoolmember',
            name='previous_jobtitle3',
            field=models.CharField(blank=True, default='Prev Job title3', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='newschoolmember',
            name='previous_jobtitle4',
            field=models.CharField(blank=True, default='Prev job title 4', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='newschoolmember',
            name='previous_jobtitle5',
            field=models.CharField(blank=True, default='Prev Job title5', max_length=75, null=True),
        ),
    ]
