# Generated by Django 5.1.1 on 2024-10-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_newschoolmember_previous_employer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newschoolmember',
            name='member_email',
            field=models.EmailField(default='abc@company.com', max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='newschoolmember',
            name='member_username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
