# Generated by Django 5.1.1 on 2024-10-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_newschoolmember_member_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newschoolmember',
            name='member_email',
            field=models.EmailField(default='abc@company.com', max_length=75),
        ),
        migrations.AlterField(
            model_name='newschoolmember',
            name='previous_employer3',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='newschoolmember',
            name='previous_employer4',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='newschoolmember',
            name='previous_employer5',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='newschoolmember',
            name='previous_jobtitle3',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='newschoolmember',
            name='previous_jobtitle4',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='newschoolmember',
            name='previous_jobtitle5',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
