# Generated by Django 5.1.1 on 2024-10-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_newschoolmember_member_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newschoolmember',
            old_name='member_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='newschoolmember',
            old_name='member_username',
            new_name='username',
        ),
    ]
