# Generated by Django 5.1.1 on 2024-10-08 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_member_password_newschoolmember_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newschoolmember',
            name='previous_employer1',
        ),
        migrations.RemoveField(
            model_name='newschoolmember',
            name='previous_employer2',
        ),
        migrations.RemoveField(
            model_name='newschoolmember',
            name='previous_employer3',
        ),
        migrations.RemoveField(
            model_name='newschoolmember',
            name='previous_employer4',
        ),
        migrations.RemoveField(
            model_name='newschoolmember',
            name='previous_employer5',
        ),
        migrations.RemoveField(
            model_name='newschoolmember',
            name='previous_jobtitle1',
        ),
        migrations.RemoveField(
            model_name='newschoolmember',
            name='previous_jobtitle2',
        ),
        migrations.RemoveField(
            model_name='newschoolmember',
            name='previous_jobtitle3',
        ),
        migrations.RemoveField(
            model_name='newschoolmember',
            name='previous_jobtitle4',
        ),
        migrations.RemoveField(
            model_name='newschoolmember',
            name='previous_jobtitle5',
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(blank=True, max_length=75, null=True)),
                ('job_title', models.CharField(blank=True, max_length=75, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='portfolio.newschoolmember')),
            ],
        ),
    ]
