# Generated by Django 5.1.1 on 2024-10-09 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_newschoolmember_previous_employer1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newschoolmember',
            name='member_mobile',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
