# Generated by Django 5.1.1 on 2024-10-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_newschoolmember_member_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newschoolmember',
            name='member_years_of_experience',
        ),
        migrations.AddField(
            model_name='newschoolmember',
            name='member_industry',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
