# Generated by Django 5.1.1 on 2024-10-10 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_remove_newschoolmember_member_years_of_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('second_name', models.CharField(max_length=45)),
                ('family_name', models.CharField(max_length=45)),
                ('mobile_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('member_title', models.CharField(max_length=75)),
                ('member_industry', models.CharField(blank=True, max_length=75, null=True)),
                ('employment_industry', models.CharField(max_length=75)),
                ('date_of_application', models.DateField(auto_now_add=True)),
                ('reason_for_joining', models.TextField(blank=True, null=True)),
                ('referred_by_name', models.CharField(blank=True, max_length=75, null=True)),
                ('referred_by_mobile', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('vetted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('member_joining_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
