# Generated by Django 5.1.1 on 2024-10-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_applicationform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenthistory',
            name='employer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='job_title',
            field=models.CharField(max_length=100),
        ),
    ]
