# Generated by Django 5.1.1 on 2024-10-16 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_employmenthistory_employer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationform',
            old_name='family_name',
            new_name='member_country',
        ),
        migrations.RenameField(
            model_name='newschoolmember',
            old_name='family_name',
            new_name='member_country',
        ),
    ]
