# Generated by Django 5.1.1 on 2024-10-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_rename_family_name_applicationform_member_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationform',
            old_name='member_country',
            new_name='family_name',
        ),
        migrations.RenameField(
            model_name='newschoolmember',
            old_name='member_country',
            new_name='family_name',
        ),
    ]
