# Generated by Django 5.1.1 on 2024-10-17 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_rename_member_country_applicationform_family_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='member_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=75, unique=True),
            preserve_default=False,
        ),
    ]
