# Generated by Django 5.1.1 on 2024-10-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_applicationform_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='member_email',
            field=models.EmailField(max_length=75),
        ),
    ]
