# Generated by Django 5.1.1 on 2024-10-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_alter_applicationform_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='member_email',
            field=models.EmailField(blank=True, max_length=75, null=True),
        ),
    ]
