# Generated by Django 5.1.1 on 2024-10-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_alter_applicationform_member_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationform',
            name='member_email',
        ),
    ]
