# Generated by Django 5.1.1 on 2024-10-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_remove_applicationform_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='member_email',
            field=models.EmailField(default='abc@company.com', max_length=75),
        ),
    ]
