# Generated by Django 5.1.1 on 2024-10-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_applicationform_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='newschoolmember',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
