# Generated by Django 5.1.1 on 2024-10-24 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_newschoolmember_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newschoolmember',
            name='profile_image',
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to='portfolio.newschoolmember')),
            ],
        ),
    ]
