# Generated by Django 5.1.1 on 2024-10-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_remove_newschoolmember_profile_image_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newschoolmember',
            name='member_email',
            field=models.EmailField(max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='newschoolmember',
            name='username',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
