# Generated by Django 5.1.1 on 2024-10-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_newschoolmember_is_active_newschoolmember_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newschoolmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('guest', 'Guest')], default='member', max_length=10),
        ),
        migrations.AlterField(
            model_name='newschoolmember',
            name='member_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
