# Generated by Django 5.1.1 on 2024-11-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_alter_profileimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newschoolmember',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('CT', 'Contractor'), ('IN', 'Intern')], max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='newschoolmember',
            name='member_country',
            field=models.CharField(blank=True, choices=[('KE', 'Kenya'), ('TZ', 'Tanzania'), ('UG', 'Uganda'), ('RW', 'Rwanda'), ('ZW', 'Zimbabwe'), ('SA', 'South Africa'), ('MZ', 'Mozambique'), ('GH', 'Ghana'), ('UAE', 'United Arab Emirates'), ('NO', 'Norway'), ('FR', 'France'), ('IT', 'Italy')], max_length=75, null=True),
        ),
    ]
