# Generated by Django 5.1.1 on 2024-11-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_newschoolmember_employment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(blank=True, default='http://localhost:5173/images/default.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
